### ISSUE TITLE
both single and double quotes are escaped

### ISSUE THREAD

**Issue by weizlini** [laxa1986/gulp-angular-embed-templates#3]
the embedded templates are wrapped in single quotes, but the double quotes are escaped as well as single quotes, leading to errors with actual angular directives. this may be an issue with typescript and angular2. currently this will not work templates that contain [routeLink]="'MyRoute'"

**Comment by laxa1986** [comment]
Hello. Thank you for attention for this plugin. I was happy to check you issue.
So, I checked Angular 2.0 templates support in version 0.1.6 and it works correctly without any issues. The reason is that in javascript '\' \"' === '\' "'
Anyway, I created versions: v0.2.0 with new strings support `strings with {params}`, then I released version 1.0.0 in which I changed behavior so for now only single quotes escaped and added a unit test checking compatibility with Angular 2.0
Also added CHANGELOG.md

and... happy New Year!!!

**Comment by OG84** [comment]
hi.

we are currently doing a proof of concept app in ng2 and we still have the issue with double quotes missing from the templates. the plugin version we use is 2.2.0. the templates come out like this: "<div class=box></div>" (quotes missing) when using @Component({ templateUrl: '....'}).

**Comment by laxa1986** [comment]
Hello. Sorry for long delay (actually I'm a kind of delivery manager and
this plugin - is my hobby, so I have very small time to support it, but I
will continue support anyway).

So, can you please send me an example? Ideally I would like to get a zip
archive with your project structure, gulp configuration and source files
that works wrong. (of course you can remove any sensible information)


2016-03-15 14:50 GMT+02:00 Christian Götze <notifications@github.com>:

> hi.
>
> we are currently doing a proof of concept app in ng2 and we still have the
> issue with double quotes missing from the templates. the plugin version we
> use is 2.2.0. the templates come out like this: "
> " (quotes missing) when using @Component <https://github.com/Component>({
> templateUrl: '....'}).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/laxa1986/gulp-angular-embed-templates/issues/3#issuecomment-196804327
>



-- 
Чекулаев Алексей

**Comment by sundriver** [comment]
This couple be related to this issue:

<img src="/images/commonwealth-trans-bw-full.gif" />

is shown as a string on the frontend, when I look at the source I see:

" <img src=/images/commonwealth-trans-bw-full.gif /> "

**Comment by gchurchley** [comment]
Given this template in a ts file:

`<div class="main-footer">
</div>`

My gulp task generates this embedded template:

`template:'<div class=main-footer></div>'`

Notice the quotes have been stripped from the class value.  This seems to happen somewhat randomly. 
When the template is large, some quotes are stripped and some are not. This causes a problem with angular2, specifically with anchor tags that contain URLs because the forward slash.

I'm not sure why the quotes are being stripped. Please could you leave them in?

**Comment by uNki23** [comment]
experiencing the same behaviour like gchurchley. quotes are missing after gulp task

**Comment by prasath-k** [comment]
It is not yet fixed then why the issue is closed ?. I am facing the same issue. The gulpfile parses the img tag as string

**Comment by VahidN** [comment]
Try defining this task with the following parameters:
```javascript
    .pipe(embedTemplates({
        debug: true,
        basePath: "./",
        sourceType: "ts",
        minimize: {
            empty: true,
            spare: true,
            quotes: true,
            dom: {
                xmlMode: true,
                lowerCaseAttributeNames: false,
                lowerCaseTags: false
            }
        }
    })) // inline templates
```

**Comment by prasath-k** [comment]
@VahidN That's not fixing the issue
